apiVersion: v1
kind: Service
metadata:
  name: kv-cache
  labels:
    app: kv-cache
spec:
  type: ClusterIP
  ports:
    - port: 7171
      targetPort: 7171
      protocol: TCP
  selector:
    app: kv-cache
